version: '3'

services:
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - .:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank